# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.cache/wt [current_project]
set_property parent.project_path D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths d:/vivado-library-master [current_project]
update_ip_catalog
set_property ip_output_repo d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/lfsr_mem_to_ublaze/lfsr_mem_to_ublaze.srcs/sources_1/imports/capstone-project/UART_TX_CTRL.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/capstone-project/btn_debounce.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/capstone-project/char_decoder.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/capstone-project/clock_divider.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/capstone-project/delay_counter.vhd
  C:/Users/poopm/OneDrive/Documents/GitHub/capstone-project/dflipflop.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/capstone-project/display_counter.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/capstone-project/lfsr.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/hdl/microblaze_wrapper.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/lfsr_mem_to_ublaze/ram.vhd
  D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/imports/lfsr_mem_to_ublaze/lfsr_mem_to_ublaze.srcs/sources_1/imports/capstone-project/xc7_top_level.vhd
}
add_files D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/microblaze.bd
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_mdm_1_0/microblaze_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_mdm_1_0/microblaze_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_clk_wiz_1_0/microblaze_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_clk_wiz_1_0/microblaze_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_clk_wiz_1_0/microblaze_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_0/microblaze_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_0/microblaze_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_0/microblaze_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_xbar_0/microblaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_mem_iface_0/microblaze_mem_iface_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_mem_iface_0/microblaze_mem_iface_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_mem_iface_0/microblaze_mem_iface_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/microblaze_PmodSD_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/microblaze_PmodSD_1_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_1_1/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/microblaze_PmodSD_2_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_PmodSD_2_1/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/sources_1/bd/microblaze/microblaze_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/constrs_1/imports/capstone-project/Basys-3-Master.xdc
set_property used_in_implementation false [get_files D:/CAPSTONE_FINAL_DESIGN/balloon_final/balloon_final.srcs/constrs_1/imports/capstone-project/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xc7_top_level -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xc7_top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xc7_top_level_utilization_synth.rpt -pb xc7_top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
